version: '2'

services:
  builder:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: flyspray
    ports:
          - "80:80"
    volumes:
      - ./flyspray/:/var/www/html/:Z
    tty: true

  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
          - "3306:3306"
          - "3396:3396"
    environment:
          MYSQL_ROOT_PASSWORD: 111
          MYSQL_DATABASE: flyspray
          MYSQL_USER: root
    tty: true
